version: "3.9"
services:
  chat-backend:
    image: bruno/chat-backend:0.0.1-SNAPSHOT
    container_name: chat-backend
    ports:
      - "8081:8080"
    environment:
      QUARKUS_PROFILE: "prod"
      QUARKUS_REDIS_HOSTS: "redis://redis:6379"
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      QUARKUS_HTTP_CORS_HEADERS: "*"
      QUARKUS_HTTP_CORS_ACCESS_CONTROL_MAX_AGE: "1800"
      QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true"
      QUARKUS_HTTP_CORS_METHODS: "GET,POST,PUT,DELETE"
    depends_on:
      - redis
    restart: no

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: no
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]